refact: Use Background Publisher instead of Push To Core
edgexfoundry/app-rfid-llrp-inventory pull request #62
Opened 2022-01-24 19:38 UTC by lenny-intel

closes #56

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-rfid-llrp-inventory/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **Requires integration testing**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **No doc updates required**

## Testing Instructions
**TBD**

## New Dependency Instructions (If applicable)
**N/A**

2022-02-14 23:11 UTC, marcpfuller requested changes

2022-02-14 23:11 UTC, lenny-intel commented on internal/inventory/app/controller.go
> +	// TODO : wrap in AddEvent request.
Nope. Removed

2022-02-14 23:14 UTC, marcpfuller submitted a review, later dismissed
LGTM

2022-02-16 21:09 UTC, ajcasagrande submitted a review, later dismissed
LGTM, just one typo.

2022-02-16 21:09 UTC, ajcasagrande commented on internal/inventory/app/app.go
> +		return errors.Wrap(err, "failed to add BackGroundPublisher")
```suggestion
		return errors.Wrap(err, "failed to add BackgroundPublisher")
```

2022-02-16 21:16 UTC, lenny-intel commented on internal/inventory/app/app.go
> +		return errors.Wrap(err, "failed to add BackGroundPublisher")
fixed

2022-02-16 21:39 UTC, ajcasagrande approved these changes

2022-02-16 21:40 UTC, merged