build(snap): update snap packaging
edgexfoundry/app-rfid-llrp-inventory pull request #64
Opened 2022-02-15 17:34 UTC by siggiskulason

This *draft* PR is a Work In Progress updating the snap packaging for this snap (fixes https://github.com/edgexfoundry/app-rfid-llrp-inventory/issues/58 )

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-rfid-llrp-inventory/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-02-16 21:44 UTC, lenny-intel reviewed
LGTM, i.e. nothing changed outside `snap/` ;-) Leaving it to other snap expected to approve.

2022-02-17 16:13 UTC, siggiskulason commented
@farshidtz - please review. Thanks!

2022-02-17 17:38 UTC, farshidtz requested changes
@siggiskulason, thanks a lot for the updated. I've made some inline comments, mostly non-functional issues. But there is a problem with env overrides set via snap options.

2022-02-17 17:38 UTC, farshidtz commented on snap/snapcraft.yaml
> +#5:  jakarta
```suggestion
# 5:  jakarta
```

2022-02-17 17:38 UTC, farshidtz commented on snap/README.md
> +|env.service.port|Service.Port|
This doesn't work:

```
$ sudo snap set edgex-app-rfid-llrp-inventory env.service.port=55555
$ sudo snap restart edgex-app-rfid-llrp-inventory
```

Logs:
```
$ sudo snap logs -f -n 100 edgex-app-rfid-llrp-inventory.app-rfid-llrp-inventory | grep localhost
...
2022-02-17T18:18:07+01:00 edgex-app-rfid-llrp-inventory.app-rfid-llrp-inventory[62516]: level=INFO ts=2022-02-17T17:18:07.503249243Z app=app-rfid-llrp-inventory source=server.go:156 msg="Starting HTTP Web Server on address localhost:59711"
...
2022-02-17T18:28:57+01:00 edgex-app-rfid-llrp-inventory.app-rfid-llrp-inventory[65781]: level=INFO ts=2022-02-17T17:28:57.713082759Z app=app-rfid-llrp-inventory source=server.go:156 msg="Starting HTTP Web Server on address localhost:59711"
```

Tried `server-bind-addr` too; it had no effect.

2022-02-18 16:51 UTC, siggiskulason commented on snap/README.md
> +|env.service.protocol|Service.Protocol|
removed from README

2022-02-18 16:51 UTC, siggiskulason commented on snap/snapcraft.yaml
>      plugs: [network, network-bind]
removed

2022-02-18 16:52 UTC, siggiskulason commented
@farshidtz - all requested issues have been resolved. Please re-review. thanks!

2022-02-18 16:56 UTC, siggiskulason commented
force-pushed to fix author/signoff issues.

2022-02-18 17:29 UTC, farshidtz approved these changes
Thanks for the updates. I tested the packaging and runtime and it works as expected.

2022-02-18 17:32 UTC, siggiskulason commented
Thanks @farshidtz . - @lenny-intel could you please approve/merge this PR? (Farshid is not on the committer list)

2022-02-20 15:36 UTC, lenny-intel approved these changes

2022-02-20 15:37 UTC, merged